### ISSUE TITLE
Resize TTY

### ISSUE THREAD

**Issue by lucymhdavies** [skybet/cali#26]
We do not currently have anything for resizing the container whenever the terminal is resized.

A naive approach to this would be to add something after
https://github.com/skybet/cali/blob/master/docker.go#L267-L271
something like:

```
        // Start resize loop
        go func() {
            for {
                tw, th, _ := terminal.GetSize(fd)
                // TODO: iff size has changed since last time we checked
                inspect, err := c.Cli.ContainerInspect(context.Background(), resp.ID)
                if err == nil && inspect.State.Running {
                    err = c.Cli.ContainerResize(context.Background(), resp.ID, types.ResizeOptions{Height: uint(th), Width: uint(tw)})
                    if err != nil {
                        log.Warnf("Unable to resize running container: %s", err)
                    }
                }

                time.Sleep(100 * time.Millisecond)
            }
        }()
```

But there would definitely be a better way of doing this.

**Comment by edupo** [comment]
I think we can catch some kind of signal and execute the resize after it.

Like [what is done to catch](https://github.com/adampointer/cali/blob/a69eb50a9b4423bbc67c095dd113e2729996236d/docker.go#L203) `ctrl+c`

**Comment by lucymhdavies** [comment]
Much better idea than doing this on a loop! 👍 

SIGWINCH looks to be the one we're interested in

**Comment by edupo** [comment]
I implemented this successfully in a project. I'll drop a PR tomorrow.

**Comment by edupo** [comment]
I completed the PR and it works for me, but testers are wellcome.

**Comment by lucymhdavies** [comment]
Thanks for this 👍 

Merged https://github.com/skybet/cali/pull/44
