### ISSUE TITLE
PullImage only pulls if the image doesn't exist locally

### ISSUE THREAD

**Issue by WheresAlice** [skybet/cali#37]
The code to pull Docker images always exits if the image exists.  There should be an option to still pull the image in order to get the latest version.  I think this just needs an extra parameter to PullImage and the if statement changing on line 361:

https://github.com/skybet/cali/blob/master/docker.go#L361

**Comment by lucymhdavies** [comment]
Duplicate of https://github.com/skybet/cali/issues/3
