### ISSUE TITLE
Do not automatically bind ~/.aws

### ISSUE THREAD

**Issue by lucymhdavies** [skybet/cali#7]
https://github.com/skybet/cali/blob/master/cli.go#L74-L78

```
	awsDir, err := t.Bind("~/.aws", "/root/.aws")
	if err != nil {
		return err
	}
	t.AddBinds([]string{awsDir})
```

Not everything needs this, and it that directory doesn't exist you're just creating an empty file on the user's machine for no reason.

It's common enough that a helper method might be worth having.
But not common enough that it should be in everything.

**Comment by edupo** [comment]
👍
